version: !!str 3

services:
  frontend:
    build:
      context: ./frontend
    image: ssbostan/london-tube-lines-frontend:latest
    depends_on:
      - backend
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - LONDON_TUBE_LINES_BACKEND_HOST_ADDR=http://backend:8080

  backend:
    build:
      context: ./backend
    image: ssbostan/london-tube-lines-backend:latest
    restart: unless-stopped
