backend:
  serviceType: ClusterIP
  imageName: ssbostan/london-tube-lines-backend:latest
  replicas: 2

frontend:
  serviceType: ClusterIP
  ingressHostAddress: london-tube-lines.b9tcluster.local
  imageName: ssbostan/london-tube-lines-frontend:latest
  replicas: 2
