backend:
  deployment:
    imageName: ssbostan/london-tube-lines-backend:latest
    replicas: 2
  service:
    type: ClusterIP

frontend:
  deployment:
    imageName: ssbostan/london-tube-lines-frontend:latest
    replicas: 2
  service:
    type: ClusterIP
  ingress:
    hostAddress: london-tube-lines.b9tcluster.local
    className: false
